In [1]:
import numpy as np
import interpolate_color as interpol

In [2]:
x1 = 1
x2 = 7
x = 4
c1 = np.array([6, 7, 4])
c2 = np.array([0, 50, 13])
color = interpol.interpolate_color(x1, x2, x, c1, c2)
print(color)

TypeError: 'int' object is not subscriptable

In [3]:
y = np.array([[3, 54], [43, 56]])
print(y[1])

[43 56]


In [7]:
x = 2
y = 3
print(x%y)

2


In [8]:
import numpy as np
import statistics
vcolors = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
color = np.zeros(3)
for i in range(3):
    i_color_palette = [vcolors[0][i], vcolors[1][i], vcolors[2][i]]
    print(i_color_palette)
    color[i] = statistics.mean(i_color_palette)
print(color)

[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[2. 3. 4.]


In [9]:
xmin = 1
xmax = 5
for x in range(xmin, xmax+1):
    print(x)

1
2
3
4
5


In [13]:
a = [[2, 4], [4, 6]]
print(len(a))

2


In [14]:
activ_peaks = [[3, 1],[2, 5]]
activ_peaks.sort(key=lambda ap: ap[0])
print(activ_peaks)

[[2, 5], [3, 1]]


In [18]:
for i in range(int(3.5), int(14.6)):
    print(i)

3
4
5
6
7
8
9
10
11
12
13


In [23]:
a = [1, 2, 3]
print(type(a))
a = np.array(a)
print(type(a))
b = np.array([a, a, a])
print(b)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
a = []
print(a)
b = [8, 4]
a.append(b)
print(a)
print(a[0])
print(a[0][1])

[]
[[8, 4]]
[8, 4]
4


In [28]:
a = [3, 6]
b = [8, 5]
c = [5, 5]
triangle1 = np.array([a, b, c])
print(triangle1)

[[3 6]
 [8 5]
 [5 5]]


In [3]:
xmin = 1
xmax = 10
slope = 1
for i in range(xmin, xmax + 1):
    print(i)
    xmin = xmin + slope
    print(xmin)

1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
